const translations = {
    "en": {
      "main-page": "Main page",
      "benefits": "Benefits",
      "advantages": "Advantages",
      "reviews": "Reviews",
      "contacts": "Contacts",
      "order": "Order",
      "under-main": "Your dream Nike",
      "main-info": "On this site you can find custom Nike sneakers of your dreams. The original company caт`t create such beautiful sneakers as we do. Good luck finding your way in the world of custom sneakers.",
      "buy-button": "Buy my Nike",
      "premium-quality": "Premium Quality",
      "indelible-paint": "Indelible paint",
      "fast-shipping": "Fast shipping",
      "reviews-title": "Reviews",
      "review1": "Sneakers are very comfortable and well painted, nothing has worn off in a year.",
      "review2": "I'm very happy with this color scheme. They match all my clothes.",
      "review3": "Just right if you need to go to a party. I use them actively, the paint is super.",
      "with-us": "With us from",
      "order-title": "Order",
      "confirm": "Confirm",
      "email-placeholder": "Write your email",
      "country-placeholder": "Your Country",
      "city-placeholder": "Your City",
      "address-placeholder": "Your Adress",
      "order-button": "Order my Nike",
      "question1": "Have a question?",
      "question2": "Have a proposal for cooperation?",
      "question3": "Advertising questions?",
      "rights": "2025 ColoRawe @All rights reserved"
    },
    "ua": {
      "main-page": "Головна сторінка",
      "benefits": "Переваги",
      "advantages": "Переваги",
      "reviews": "Відгуки",
      "contacts": "Контакти",
      "order": "Замовлення",
      "under-main": "Твої омріяні Nike",
      "main-info": "На цьому сайті ви знайдете кастомні кросівки Nike своєї мрії. Оригінальна компанія не може створити такі гарні кросівки, як ми. Успіхів у пошуку власного шляху у світі кастомних кросівок.",
      "buy-button": "Купити мій Nike",
      "premium-quality": "Преміум якість",
      "indelible-paint": "Незмивна фарба",
      "fast-shipping": "Швидка доставка",
      "reviews-title": "Відгуки",
      "review1": "Кросівки дуже зручні та добре пофарбовані, нічого не стерлося за рік.",
      "review2": "Я дуже задоволена цією кольоровою гамою. Вони підходять до всього мого одягу.",
      "review3": "Саме те, що потрібно для вечірки. Я активно їх використовую, фарба супер.",
      "with-us": "З нами з",
      "order-title": "Замовлення",
      "confirm": "Підтвердити",
      "email-placeholder": "Введіть ваш email",
      "country-placeholder": "Ваша Країна",
      "city-placeholder": "Ваше Місто",
      "address-placeholder": "Ваша Адреса",
      "order-button": "Замовити мій Nike",
      "question1": "Маєте питання?",
      "question2": "Є пропозиція співпраці?",
      "question3": "Питання з реклами?",
      "rights": "2025 ColoRawe @Всі права захищені"
    }
  };